# Generated by Django 3.2 on 2021-08-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='link',
            field=models.CharField(default='register ', max_length=100),
            preserve_default=False,
        ),
    ]
