# Generated by Django 3.2 on 2021-08-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_chennairestaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='chennairestaurant',
            name='link',
            field=models.CharField(default='dishes', max_length=100),
            preserve_default=False,
        ),
    ]
